export const ADD_PARKS = 'ADD_PARKS'
export const ADD_CAMPSITES = 'ADD_CAMPSITES'
export const UPDATE_POSITION = 'UPDATE_POSITION'
export const TOGGLE_STARRED = 'TOGGLE_STARRED'
export const NOOP = 'NOOP'
